import { basename, dirname, extname, join, relative, resolve } from 'node:path';
import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { Project, ScriptTarget, ModuleKind, ts } from 'ts-morph';

import { exists } from '../helpers';
import type { Logger } from '@mahameru/diatrema';

type GeneratorOptions = {
    dev: boolean;
    rootPath: string;
    appPath: string;
    routesPath: string;
    modulesPath: string;
    outputTypesPath: string;
    sourceDirPath: string;
}

type GeneratorDependencies = {
    dataSources?: Record<string, any>;
    logger?: Logger;
}

export class Generator {
    public readonly options: GeneratorOptions;
    protected readonly dependencies: GeneratorDependencies;

    constructor(initialOptions: GeneratorOptions, dependencies: GeneratorDependencies = {}) {
        this.options = initialOptions;
        this.dependencies = dependencies;
    }

    async start() {
        const routesIndexFilePath = join(this.options.sourceDirPath, 'routes', 'route.ts');
        const moduleSourcePath = join(this.options.sourceDirPath, 'modules');

        if (!(await exists(moduleSourcePath)))
            await mkdir(moduleSourcePath, { recursive: true });

        if (!(await exists(dirname(routesIndexFilePath))) || !(await exists(routesIndexFilePath)))
            await this.generateRouteIndexFile(routesIndexFilePath);

        await mkdir(this.options.outputTypesPath, { recursive: true });

        await this.generateRouteTypes();
        await this.generateModulesDts();
        await this.generateInstancesDTS();
        await this.generateMahameruContainerDTS();
        await this.generateEnvDTS();
        await this.generateBarrelIndexFile();
        await this.generateMahameruDTSFile();
        await this.appendMahameruDTSToTsConfig();
    }

    protected async generateRouteIndexFile(routesIndexFilePath: string) {
        await mkdir(dirname(routesIndexFilePath), { recursive: true });

        const template = `import { type RouteHandler, MahameruResponse } from 'mahameru'

export const GET: RouteHandler = () => {
    return MahameruResponse.json({
        success: true,
        message: 'Welcome to MahameruJS!'
    })
}
`;

        await writeFile(routesIndexFilePath, template, 'utf-8');
    }

    protected async generateRouteTypes() {
        const routesPath = this.options.sourceDirPath;
        const foundPaths: string[] = [];

        async function scan(dir: string, currentRoute = '') {
            if (!(await exists(dir)))
                return;

            const files = await readdir(dir);

            for (const file of files) {
                const fullPath = join(dir, file);
                const statRes = await stat(fullPath);

                if (statRes.isDirectory()) {
                    const folderName = file.startsWith('[') && file.endsWith(']')
                        ? `:${file.slice(1, -1)}`
                        : file;

                    const nextRoute = currentRoute === '' && folderName === 'routes'
                        ? ''
                        : (currentRoute === '/' ? `/${folderName}` : `${currentRoute}/${folderName}`);

                    await scan(fullPath, nextRoute);
                } else if (file === 'route.ts' || file === 'route.js') {
                    foundPaths.push(currentRoute === '' ? '/' : currentRoute);
                }
            }
        }

        await scan(routesPath, '');

        const uniquePaths = Array.from(new Set(['/', ...foundPaths]));
        const routeUnion = uniquePaths.map((p) => `'${p}'`).join(' | ') || `'/'`;
        const template = `// Do not edit this file, it is generated by MahameruJS\n\nimport { RouteObject } from 'mahameru';\n\ntype MahameruGeneratedRoutes = ${routeUnion};\n\ndeclare module 'mahameru' {\n\texport interface RegisterRoutes {\n\t\troutes: MahameruGeneratedRoutes | RouteObject<MahameruGeneratedRoutes>;\n\t}\n}\n`;
        const outputPath = join(this.options.outputTypesPath, 'routes.d.ts');

        await writeFile(outputPath, template, { encoding: 'utf-8' });
    }

    protected async generateModulesDts(): Promise<void> {
        const outputFilePath = join(this.options.outputTypesPath, 'modules.d.ts');
        const sourceDir = this.options.modulesPath;
        const absoluteSourceDir = resolve(sourceDir);
        const absoluteOutputDir = resolve(outputFilePath);
        const outputDirName = dirname(absoluteOutputDir);
        const project = new Project();

        project.addSourceFilesAtPaths(`${absoluteSourceDir}/**/*.ts`);

        let importStatements = '';
        let interfaceProperties = '';

        project.getSourceFiles().forEach((sourceFile) => {
            const filePath = sourceFile.getFilePath();
            const fileName = sourceFile.getBaseName();

            if (fileName === 'index.ts' || fileName.endsWith('.d.ts'))
                return;

            const defaultClass = sourceFile.getClasses().find(c => c.isDefaultExport());

            if (!defaultClass)
                return;

            const className = defaultClass.getName();

            if (!className)
                return;

            let relativePath = relative(outputDirName, filePath);
            relativePath = relativePath.replace(/\\/g, '/').replace(/\.ts$/, '');

            if (!relativePath.startsWith('.'))
                relativePath = './' + relativePath;


            importStatements += `import ${className} from '${relativePath}';\n`;

            const propertyName = className.charAt(0).toLowerCase() + className.slice(1);

            interfaceProperties += `\t${propertyName}: ${className};\n`;
        });

        const fileContent = `${importStatements}
export interface Modules {
${interfaceProperties}}
`;

        await writeFile(absoluteOutputDir, fileContent, 'utf-8');
    }

    protected async generateInstancesDTS(): Promise<void> {
        try {
            const initiatorPath = join(this.options.rootPath, 'src', 'initiator.ts');
            const outputPath = join(this.options.outputTypesPath, 'instances.d.ts');

            if (!(await exists(initiatorPath)))
                return;

            const project = new Project({
                compilerOptions: {
                    target: ScriptTarget.ESNext,
                    module: ModuleKind.ESNext,
                    strict: true,
                    baseUrl: '.',
                    paths: {
                        '@/*': ['src/*'],
                    },
                },
                skipAddingFilesFromTsConfig: true,
            });

            const sourceFile = project.addSourceFileAtPath(initiatorPath);

            const outputSourceFile = project.createSourceFile(
                outputPath,
                '',
                { overwrite: true }
            );

            const typeChecker = project.getTypeChecker();

            const defaultExportSymbol = sourceFile.getDefaultExportSymbol();

            if (!defaultExportSymbol) {
                throw new Error(`No default export found in ${initiatorPath}`);
            }

            const exportDeclaration = defaultExportSymbol.getDeclarations()[0];

            if (!exportDeclaration) {
                throw new Error(`Could not find declaration for default export in ${initiatorPath}`);
            }

            const exportType = typeChecker.getTypeOfSymbolAtLocation(
                defaultExportSymbol,
                exportDeclaration
            );

            const signatures = exportType.getCallSignatures();

            if (signatures.length === 0) {
                throw new Error('Default export is not a function');
            }

            let returnType = signatures[0].getReturnType();

            if (returnType.getText().startsWith('Promise<')) {
                const args = returnType.getTypeArguments();

                if (args.length > 0) {
                    returnType = args[0];
                }
            }

            const imports = new Map<string, Set<string>>();
            let interfaceBody = 'export interface Instances {\n';

            for (const property of returnType.getProperties()) {
                const propertyType =
                    property.getTypeAtLocation(exportDeclaration) ??
                    property.getDeclaredType();

                const typeText = typeChecker.compilerObject.typeToString(
                    propertyType.compilerType,
                    exportDeclaration.compilerNode,
                    ts.TypeFormatFlags.UseFullyQualifiedType |
                    ts.TypeFormatFlags.NoTruncation
                );

                interfaceBody += `\t${property.getName()}: ${typeText};\n`;

                for (const importDecl of sourceFile.getImportDeclarations()) {
                    const targetFile = importDecl.getModuleSpecifierSourceFile();

                    if (!targetFile) {
                        continue;
                    }

                    const matchedImports = importDecl
                        .getNamedImports()
                        .filter(named => {
                            const importName = named.getName();

                            return (
                                propertyType.getText().includes(importName) ||
                                propertyType.getSymbol()?.getName() === importName ||
                                propertyType.getAliasSymbol()?.getName() === importName
                            );
                        });

                    if (matchedImports.length === 0) {
                        continue;
                    }

                    const moduleSpecifier =
                        outputSourceFile.getRelativePathAsModuleSpecifierTo(targetFile);

                    if (!imports.has(moduleSpecifier)) {
                        imports.set(moduleSpecifier, new Set());
                    }

                    const set = imports.get(moduleSpecifier)!;

                    for (const named of matchedImports) {
                        set.add(named.getText());
                    }
                }
            }

            interfaceBody += '}';

            const importStatements = [...imports.entries()]
                .map(([specifier, names]) => {
                    return `import { ${[...names].sort().join(', ')} } from '${specifier}';`;
                })
                .join('\n');

            const content = `${importStatements ? `${importStatements}\n\n` : ''}${interfaceBody}\n`;

            await writeFile(outputPath, content, 'utf8');
        } catch (error: any) {
            if (
                error.code === 'ERR_MODULE_NOT_FOUND' ||
                error.code === 'MODULE_NOT_FOUND'
            ) {
                console.error('❌ ts-morph tidak ditemukan.');
                console.error('Jalankan: npm install --save-dev ts-morph');

                throw new Error('ts-morph is required as devDependency');
            }

            if (this.dependencies.logger)
                this.dependencies.logger.error(
                    'Error generating instances.d.ts:',
                    error
                );

            throw error;
        }
    }

    protected async generateMahameruContainerDTS(): Promise<void> {
        const dependenciesDtsFilePath: string[] = [];
        const modulesDtsFilePath = join(this.options.outputTypesPath, 'modules.d.ts');
        const instancesDtsFilePath = join(this.options.outputTypesPath, 'instances.d.ts');

        if (await exists(modulesDtsFilePath))
            dependenciesDtsFilePath.push(modulesDtsFilePath);

        if (await exists(instancesDtsFilePath))
            dependenciesDtsFilePath.push(instancesDtsFilePath);

        if (dependenciesDtsFilePath.length === 0)
            return;

        const outputFilePath = join(this.options.outputTypesPath, 'mahameru-container.d.ts');
        const project = new Project();
        const sourceFile = project.createSourceFile(outputFilePath, {}, { overwrite: true });
        const interfaceNames: string[] = [];

        for (const filePath of dependenciesDtsFilePath) {
            const fileNameWithoutExt = basename(filePath, extname(filePath)).replace('.d', '');
            const depFile = project.addSourceFileAtPath(filePath);
            const exportedInterfaces = depFile.getInterfaces().filter(i => i.isExported());

            for (const intf of exportedInterfaces) {
                const interfaceName = intf.getName();
                interfaceNames.push(interfaceName);

                sourceFile.addImportDeclaration({
                    namedImports: [interfaceName],
                    moduleSpecifier: `./${fileNameWithoutExt}`
                });
            }
        }

        const moduleDeclaration = sourceFile.addModule({
            name: "'mahameru'",
            hasDeclareKeyword: true
        });

        moduleDeclaration.addInterface({
            name: 'MahameruContainer',
            isExported: true,
            extends: interfaceNames
        });

        const template = sourceFile.getFullText();
        await writeFile(outputFilePath, template, 'utf8');
    }

    protected async generateBarrelIndexFile(): Promise<void> {
        try {
            if (!(await exists(this.options.outputTypesPath)))
                return;

            const items = await readdir(this.options.outputTypesPath).catch(error => {
                if (error.code === 'ENOENT')
                    return [];

                throw error;
            });

            const exportLinesPromises = items.map(async (item) => {
                if (item.startsWith('index.'))
                    return null;

                const fullPath = join(this.options.outputTypesPath, item);
                const stats = await stat(fullPath);
                const isDirectory = stats.isDirectory();

                if (isDirectory || item.endsWith('.ts') || item.endsWith('.js')) {
                    let nameWithoutExt = '';

                    if (isDirectory) {
                        nameWithoutExt = item;
                    } else {
                        nameWithoutExt = item.split('.d')[0];
                    }

                    const targetPath = '.' + '/' + nameWithoutExt;

                    return `export * from '${targetPath}'`;
                }

                return null;
            });

            const exportLines = (await Promise.all(exportLinesPromises))
                .filter((value): value is string => value !== null);

            if (exportLines.length === 0)
                return;

            const fileContent = exportLines.join('\n') + '\n';
            const outputPath = join(this.options.outputTypesPath, 'index.d.ts');
            await writeFile(outputPath, fileContent, 'utf-8');
        } catch (error) {
            if (this.dependencies.logger)
                this.dependencies.logger.error(`Failed to create index.d.ts:`, error);
        }
    }

    protected async generateDataSourcesTypes() {
        if (!this.dependencies.dataSources)
            return;

        const lines = Object.keys(this.dependencies.dataSources).map((name) => `    ${name}: DataSource;`);
        const hasDataSources = lines.length > 0;
        const dataSourceTemplate = hasDataSources
            ? `// Do not edit this file, it is generated by MahameruJS\n\nimport type { DataSource } from "typeorm";\n\ndeclare module 'mahameru' {\n\texport interface DataSources {\n\t\t${lines.join('\n')}\n\t}\n\n\texport interface PreInitContext {\n\t\tdataSources: DataSources;\n\t}\n}\n`
            : `// Do not edit this file, it is generated by MahameruJS\n\ndeclare module 'mahameru' {}\n`;
        const outputPath = join(this.options.appPath, 'types', 'dataSources.d.ts');

        try {
            await mkdir(dirname(outputPath), { recursive: true });
            await writeFile(outputPath, dataSourceTemplate, 'utf-8');

            if (this.dependencies.logger)
                this.dependencies.logger.info(`Data sources types generated successfully at ${outputPath}`);
        } catch (error) {
            if (this.dependencies.logger)
                this.dependencies.logger.error('Error generating data sources types', error);
        }
    }

    protected async generateMahameruDTSFile() {
        const typeIndexFile = join(this.options.outputTypesPath, 'index.d.ts');

        if (!(await exists(typeIndexFile)))
            return;

        const toRelative = (path: string) => path.replace(this.options.rootPath, '.').replace(/\\/g, '/');
        const dTSContents = `/// <reference path="${toRelative(typeIndexFile)}" />\n\n// Do not edit this file, it is generated by MahameruJS\n`;

        const dTSfile = join(this.options.rootPath, 'mahameru.d.ts');
        await writeFile(dTSfile, dTSContents, { encoding: 'utf-8' });
    }

    protected async appendMahameruDTSToTsConfig() {
        const tsConfigPath = join(this.options.rootPath, 'tsconfig.json');

        if (!(await exists(tsConfigPath)))
            return;

        try {
            const tsConfig = JSON.parse(await readFile(tsConfigPath, 'utf-8'));

            if (tsConfig.include) {
                if (!tsConfig.include.includes('mahameru.d.ts'))
                    tsConfig.include.push('mahameru.d.ts');
            } else {
                tsConfig.include = ['mahameru.d.ts'];
            }

            await writeFile(tsConfigPath, JSON.stringify(tsConfig, null, 2), 'utf-8');
        } catch (error) {
            if (this.dependencies.logger)
                this.dependencies.logger.error(`Failed to read tsconfig.json:`, error);
        }
    }

    protected async generateEnvDTS() {
        const defaultEnvFilePath = join(this.options.rootPath, '.env');
        const envFilePath = join(this.options.rootPath, `.env.${this.options.dev ? "development" : "production"}`);
        const envLocalFilePath = join(this.options.rootPath, '.env.local');
        const filesToLoad = [defaultEnvFilePath, envFilePath, envLocalFilePath];
        const envForMahameru: Record<string, string> = {};
        const outputTypesFilePath = join(this.options.outputTypesPath, 'mahameru-env.d.ts');

        for (const filePath of filesToLoad) {
            if (await exists(filePath)) {
                try {
                    const content = await readFile(filePath, 'utf-8');
                    const lines = content.split(/\r?\n/);

                    for (const line of lines) {
                        const trimmed = line.trim();
                        if (!trimmed || trimmed.startsWith('#')) continue;

                        const equalIndex = trimmed.indexOf('=');
                        if (equalIndex === -1) continue;

                        const key = trimmed.substring(0, equalIndex).trim();
                        let value = trimmed.substring(equalIndex + 1).trim();

                        if (key.startsWith('MAHAMERU__')) {
                            if ((value.startsWith('"') && value.endsWith('"')) ||
                                (value.startsWith("'") && value.endsWith("'"))) {
                                value = value.slice(1, -1);
                            }

                            const cleanKey = key.replace(/^MAHAMERU__/, '');
                            envForMahameru[cleanKey] = value;
                        }
                    }
                } catch (error) {
                    console.error(`Failed to read ${filePath}:`, error);
                }
            }
        }

        if (Object.keys(envForMahameru).length === 0)
            return;

        const properties = Object.keys(envForMahameru)
            .map(key => `\treadonly ${key}: string;`)
            .join('\n');

        const template = `// Do not edit this file, it is generated by MahameruJS\n\ninterface MahameruGlobalEnv {\n${properties}\n}\n\ndeclare global {\n\tvar mahameruEnv: MahameruGlobalEnv;\n}\n\nexport {};\n`;

        try {
            await writeFile(outputTypesFilePath, template, 'utf-8');
        } catch (error) {
            console.error(`Failed to generate env.d.ts:`, error);
        }
    }
}
