import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, parse } from 'node:path';
import { TsConfigJson } from 'type-fest';

export async function generateRouteTypes(routesPath: string, outputPath: string) {
  const foundPaths: string[] = [];

  async function scan(dir: string, currentRoute = '') {
    if (!existsSync(dir)) return;

    const files = await readdir(dir);

    for (const file of files) {
      const fullPath = join(dir, file);
      const statRes = await stat(fullPath);

      if (statRes.isDirectory()) {
        await scan(fullPath, `${currentRoute}/${file}`);
      } else if (file === 'route.ts' || file === 'route.js') {
        foundPaths.push(currentRoute === '' ? '/' : currentRoute);
      }
    }
  }

  await scan(routesPath);

  const routeUnion = foundPaths.map((p) => `'${p}'`).join(' | ') || 'string';
  const template = `// Do not edit this file, it is generated by MahameruJS

import { RouteObject } from 'mahameru';

type MahameruGeneratedRoutes = ${routeUnion};

declare module 'mahameru' {
	export interface RegisterRoutes {
		routes: MahameruGeneratedRoutes | RouteObject<MahameruGeneratedRoutes>;
	}
}
`;

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, template.trim(), 'utf-8');
}

export async function generateDataSourceTypes(databasesPath: string, outputPath: string) {
  const dataSourceNames: string[] = [];

  if (!existsSync(databasesPath)) {
    if (existsSync(outputPath)) {
      await rm(outputPath, { force: true });

      return;
    }

    return;
  }

  const entries = await readdir(databasesPath);

  for (const entry of entries) {
    const fullPath = join(databasesPath, entry);
    const statRes = await stat(fullPath);

    if (statRes.isDirectory()) {
      dataSourceNames.push(entry);
    }
  }

  const hasDataSources = dataSourceNames.length > 0;

  if (!hasDataSources) return;

  const template = `// Do not edit this file, it is generated by MahameruJS

import type { DataSource } from "typeorm";

declare module 'mahameru' {
	export interface DataSources {
${dataSourceNames.map((name) => `		${name}: DataSource;`).join('\n')}
	}

	export interface PreInitContext {
		dataSources: DataSources;
	}
}
`;

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, template.trim(), 'utf-8');
}

export async function generateBarrelIndexFile(targetDir: string) {
  try {
    const items = await readdir(targetDir);

    const exportLinesPromises = items.map(async (item) => {
      if (item === 'index.d.ts' || item === 'index.ts' || item === 'index.js') return null;

      const fullPath = join(targetDir, item);
      const stats = await stat(fullPath);
      const isDirectory = stats.isDirectory();

      if (isDirectory || item.endsWith('.ts') || item.endsWith('.js')) {
        const nameWithoutExt = parse(item).name;
        return `export * from './${nameWithoutExt}'`;
      }

      return null;
    });

    const exportLines = (await Promise.all(exportLinesPromises)).filter(
      (line): line is string => line !== null,
    );

    const fileContent = exportLines.join('\n') + '\n';

    const outputPath = join(targetDir, 'index.d.ts');
    await writeFile(outputPath, fileContent, 'utf-8');
  } catch (error) {
    console.error(`Failed to create index.d.ts:`, error);
  }
}

export async function generateMahameruDts(outputPath: string) {
  const dTSContents = `/// <reference path="./.mahameru/types/index.d.ts" />

// Do not edit this file, it is generated by MahameruJS
`;

  await writeFile(outputPath, dTSContents, 'utf-8');

  try {
    const tsconfigJson = join(process.cwd(), 'tsconfig.json');

    if (!existsSync(tsconfigJson)) throw new Error('tsconfig.json not found');

    const tsconfigJsonContents = JSON.parse(await readFile(tsconfigJson, 'utf-8')) as TsConfigJson;

    if (typeof tsconfigJsonContents.include === 'undefined') {
      tsconfigJsonContents.include = ['mahameru.d.ts'];
    } else if (!tsconfigJsonContents.include.includes('mahameru.d.ts')) {
      tsconfigJsonContents.include.push('mahameru.d.ts');
    }

    await writeFile(tsconfigJson, JSON.stringify(tsconfigJsonContents, null, 2), 'utf-8');
  } catch (error) {
    console.error(error);
  }
}
